version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: dmitriprilepski/get-started:part1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    command: ["service2", "8080"]
    volumes:
      - services:/mnt
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
volumes:
  services:
