version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: friendlyhello:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    command: ["servicename.txt", "80"]
    volumes:
      - services:/mnt
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
volumes:
  services:
